language: r
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - drat

before_install:
  - tlmgr install fancyvrb units
  - sudo apt-get update
  - sudo apt-get install -y libpng-dev

#before_script:
#  - make

after_success:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
